### ISSUE TITLE
controlling the hlookat of the scene

### ISSUE THREAD

**Issue by eliecermarchante** [lonelyelk/krpano-arrows#2]
Hi, 

Is there a way to control the hlookat of the landing scene after clicking on the arrow?
In the following example: http://your360virtual.com/obasa/saskatoon/vtour/tour.html 
when you go from scene 3 (IMG3) to scene 4 (IMG4), or vice-versa (from scene 4 to 3), the landing panorama is out of place. I tried to increase/decrease the value of hdir in the layer inside the scene, but that not only change the orientation of the arrow, it also affects the hlookat in the landing panorama.

**Comment by eliecermarchante** [comment]
A solution could be to use view.hlookat inside the onclick and after the loadscene, but that screws the arrows orientations:

`<connection name="scene_IMG3" hdir="1" onclick="loadscene(scene_IMG3, null, KEEPVIEW, BLEND(0.2));set(view.hlookat,350.4);" shape="custom-arrow-shape" shadowstyle="default-shadow"  shadow="true"/>`

**Comment by eliecermarchante** [comment]
I finish adjusting the panorama images using prealign="X|Y|Z" inside the scene. Something like:
`<image prealign="0|-8|0" type="CUBE" multires="true" tilesize="512">`
Example: http://your360virtual.com/obasa/saskatoon/vtour/tour.html  

It tooks forever. It could be nice to have some tool part of the arrows plugin to align the panos with the arrows. One question: Is possible to move the arrows closer to the floor?

**Comment by lonelyelk** [comment]
Yes, [prealign](http://krpano.com/docu/xml/#image.prealign) is the way to go. What you want to do is to set all prealign horizontal angles so that `hlookat=0` would look at the same global direction, say north, for all panoramas. In that case connection's `hdir` would be the true azimuth from one point to another. You can achieve that by shooting the first panorama shot always at the same direction (say north) and make this direction your front cube side. Middle of your first north shot should be in the middle of front side. Or you can use one wall in the way that when you look directly at it (floor and ceiling lines are horizontal) all your panoramas' `hlookat` would be the same.

**Comment by eliecermarchante** [comment]
Thanks for the suggestion. I really appreciate it.
Is there any way to move the arrows closer to the floor?

**Comment by lonelyelk** [comment]
You can change first point of `<functionv>` tag with `vlookat="0"` to greater `posv`. In example. It sets the vertical angle to the center of arrows rotation when the user is looking horizontally.

**Comment by eliecermarchante** [comment]
But I don't want the arrow to go to the ceiling. When functionv is used, the arrows are going all the way up to the ceiling.

**Comment by eliecermarchante** [comment]
Never mind... the point p1 controls that. Thanks for your assistance.
