### ISSUE TITLE
how to add text to arrow ?

### ISSUE THREAD

**Issue by luckyloong** [lonelyelk/krpano-arrows#7]
I want to add text to the arrow. What do I need to do?Just like this effect

![Alt text](https://www.52kfz.com/1.png)
![Alt text](https://www.52kfz.com/2.png)

**Comment by lonelyelk** [comment]
It depends on your programming skills. For now there is no built in way to add distorted text. I can add it as a feature request.

Otherwise, there is a way to draw your text as if it were arrows with shape inside [arrow tag](https://krpano.com/plugins/userplugins/arrows/#arrow) without a shadow and in a particular shape style. But it might look ugly.

**Comment by luckyloong** [comment]
Thank you very much. Can you give me some ideas? I'm not sure if the hot text can be implemented or replaced by text or pictures. We need text display very much, and we don't have the ability to modify your code at the moment.

**Comment by lonelyelk** [comment]
I guess that is all I have. May be you are better off using images and distorting them. You would have to look through forums for that.
